version: '3.9'

services:
  backend:
    build: .
    container_name: inventory-backend
    ports:
      - "4000:4000"
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma db seed &&
        npm run start:prod
      "

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  pgdata:
